// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UmbracoRaffle.Data;

namespace UmbracoRaffle.Migrations
{
    [DbContext(typeof(RaffleDbContext))]
    [Migration("20200409105735_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("UmbracoRaffle.Models.Raffle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .HasColumnType("TEXT");

                    b.Property<int>("Serialnumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Raffle");
                });

            modelBuilder.Entity("UmbracoRaffle.Models.Serialnumber", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Number");

                    b.ToTable("Serialnumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
